### ISSUE TITLE
small decimals

### ISSUE THREAD

**Issue by szymonk92** [616slayer616/natorder#10]
While testing, I came across issue with small numbers, first list works fine:
`Arrays.asList(".3", "0.6", "0.7", "0.8", "0.9", "1.0", "1.0b", "1.0c", "1.1", "1.2", "1.3");`
However, adding `.00003` as first number breaks the sorting and returns:
```
java.lang.AssertionError: 
Expected :[0.00003, 0.3, 0.6, 0.7, 0.8, 0.9, 1.0, 1.0b, 1.0c, 1.1, 1.2, 1.3]
Actual   :[0.6, 0.7, 0.8, 0.9, 0.00003, 0.3, 1.0, 1.0b, 1.0c, 1.1, 1.2, 1.3]
```

**Comment by 616slayer616** [comment]
Thank you for your submission.
I will have a look at it.

**Comment by 616slayer616** [comment]
Do you want to have a look at this? https://github.com/616slayer616/natorder/pull/11
